### ISSUE TITLE
Architecture Design

### ISSUE THREAD

**Issue by tramstheman** [North-Vine-Engineering/PythonAdventure#3]
We need to design the game engine architecture

**Comment by tramstheman** [comment]
Architecture is done

**Comment by GEvanscsumb** [comment]
I'm assuming that there shouldn't be a warp from room 5 to 2 when going south so I removed it. If this was intentional please double check the code

**Comment by akatrent** [comment]
Yea I saw that as well.  I didn't know if that was intentional or not.

**Comment by tramstheman** [comment]
are you referring to the code base or the document?

**Comment by tramstheman** [comment]
When you close this, don't forget to move it to complete on the kanban.
